server:
  port: 6789

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_payments
    username: root
    password: user123

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

    #url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    #username: ${MYSQLUSER}
    #password: ${MYSQLPASSWORD}
